language: go
sudo: false
go_import_path: github.com/roshanr83/go-oauth2
go:
- 1.11.4
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE goauth;'
- go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)