language: go
sudo: false
go_import_path: github.com/roshanr83/goOauth2
go:
- 1.9
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE goauth;'
- go get ./...

script:
- go test

after_success:
- bash <(curl -s https://codecov.io/bash)